import type { PlaylistTrack } from '@/types'

export const blueEyesBlackCoralPlaylist: PlaylistTrack[] = [
  { chapter: 'Minor Keys', song: 'The House of the Rising Sun', artist: 'Bob Dylan' },
  { chapter: 'No Looking Back', song: 'Life Is Just a Tire Swing', artist: 'Jimmy Buffett' },
  { chapter: 'The Vow', song: 'Doctor My Eyes', artist: 'Jackson Browne' },
  { chapter: 'Corvette', song: 'Big Shot', artist: 'Billy Joel' },
  { chapter: 'Shelly', song: "Swayin' to the Music", artist: 'Johnny Rivers' },
  { chapter: 'Chainsaw', song: 'The Great Filling Station Holdup', artist: 'Jimmy Buffett' },
  { chapter: 'Madonna', song: 'Borderline', artist: 'Madonna' },
  { chapter: "Boxer's Jab", song: 'A Horse with No Name', artist: 'America' },
  { chapter: 'Blue Train', song: 'Take Five', artist: 'Dave Brubeck Quartet' },
  { chapter: 'Triple Jump', song: "You'll Accomp'ny Me", artist: 'Bob Seger' },
  { chapter: 'Dress Shop', song: 'Saturday Night Special', artist: 'Lynyrd Skynyrd' },
  { chapter: 'Kind of Blue', song: 'American Pie', artist: 'Don McLean' },
  { chapter: 'Brother', song: 'Ventura Highway', artist: 'America' },
  { chapter: 'Mirror', song: 'Spiegel im Spiegel', artist: 'Arvo Pärt' },
  { chapter: 'Buffers', song: 'The Stranger', artist: 'Billy Joel' },
  { chapter: 'Rum Raisin', song: 'Make Me Smile', artist: 'Chicago' },
  { chapter: 'Masquerade', song: 'The Masquerade is Over', artist: 'Nancy Wilson' },
  { chapter: 'Words', song: 'A Country Boy Can Survive', artist: 'Hank Williams Jr.' },
  { chapter: 'Little Brother', song: 'Dust in the Wind', artist: 'Kansas' },
  { chapter: 'Piggyback', song: 'Into the Mystic', artist: 'Van Morrison' },
  { chapter: 'A Stereo, Guitar, and a Gun', song: 'Play Guitar', artist: 'John Cougar' },
  { chapter: 'The Straw', song: 'Night Moves', artist: 'Bob Seger' },
  { chapter: 'Roots', song: 'I Go Crazy', artist: 'Paul Davis' },
  { chapter: 'Tenth Grade', song: 'Adam Raised a Cain', artist: 'Bruce Springsteen' },
  { chapter: 'The Judge', song: 'Simple Man', artist: 'Lynyrd Skynyrd' },
  { chapter: 'Invisible Man', song: 'Every Breath You Take', artist: 'The Police' },
  { chapter: 'No Emily Post', song: 'Summer Breeze', artist: 'Seals and Crofts' },
  { chapter: 'Soul Food', song: "Maybe God Is Tryin' To Tell You Somethin'", artist: 'Quincy Jones' },
  { chapter: 'Neon Lights', song: "You're No Good", artist: 'Linda Ronstadt' },
  { chapter: 'Thunder Road', song: 'Thunder Road', artist: 'Bruce Springsteen' },
  { chapter: 'Black Coral', song: 'Rocky Mountain High', artist: 'John Denver' },
  { chapter: 'A Cook and Some Pictures', song: 'Folsom Prison Blues', artist: 'Johnny Cash' },
  { chapter: 'Snapped', song: 'Talk About the Passion', artist: 'R.E.M' },
  { chapter: 'Most Wanted', song: 'Badlands', artist: 'Bruce Springsteen' },
  { chapter: 'Kudos', song: 'Fire and Rain', artist: 'James Taylor' },
  { chapter: 'Chicken Lady', song: 'You May Be Right', artist: 'Billy Joel' },
  { chapter: 'You!', song: 'More Than A Feeling', artist: 'Boston' },
  { chapter: 'Jaws', song: "Searchin' So Long", artist: 'Chicago' },
  { chapter: 'Greyhound', song: 'Changes in Latitude, Changes in Attitude', artist: 'Jimmy Buffett' },
  { chapter: 'Peaches', song: "Annie's Song", artist: 'John Denver' },
  { chapter: 'Epilogue', song: "I'm So Glad", artist: 'The Staple Singers' },
]
