import type { PlaylistTrack } from '@/types'

export const matecumbeIslandPlaylist: PlaylistTrack[] = [
  { chapter: 'Broken Promises', song: 'Feels Like the First Time', artist: 'Foreigner' },
  { chapter: 'Trouble Couch', song: 'The River', artist: 'Bruce Springsteen' },
  { chapter: 'Roller Coasters', song: 'Jungle Love', artist: 'Steve Miller Band' },
  { chapter: 'Gammie and Mr. D', song: 'Rain On the Scarecrow', artist: 'John Mellencamp' },
  { chapter: 'Luckiest SOB in Georgia', song: 'Turn the Page', artist: 'Bob Seger' },
  { chapter: 'Bo Lauder', song: 'Dust in the Wind', artist: 'Kansas' },
  { chapter: 'Old Judy', song: 'You Make Me Feel Like Dancing', artist: 'Leo Sayer' },
  { chapter: 'College Boy', song: 'Southern Cross', artist: 'Crosby, Stills & Nash' },
  { chapter: 'Cheese', song: 'Tom Sawyer', artist: 'Rush' },
  { chapter: 'Eagle Eye', song: 'Family Tradition', artist: 'Hank Williams, Jr.' },
  { chapter: 'Trust', song: 'Smoky Mountain Rain', artist: 'Ronnie Milsap' },
  { chapter: 'Tab', song: 'Brown Eyed Girl', artist: 'Van Morrison' },
  { chapter: "Fool's Gold", song: 'Driven to Tears', artist: 'The Police' },
  { chapter: 'Lonesome Dove', song: 'East Bound and Down', artist: 'Jerry Reed' },
  { chapter: 'Diver Down', song: 'Gold Dust Woman', artist: 'Fleetwood Mac' },
  { chapter: 'Floyd', song: 'Trying to Reason With Hurricane Season', artist: 'Jimmy Buffett' },
  { chapter: "Caesar's Palace", song: 'Master Blaster', artist: 'Stevie Wonder' },
  { chapter: 'Warning!', song: "Don't Come Around Here No More", artist: 'Tom Petty' },
  { chapter: 'Coccinella', song: 'Gimme Shelter', artist: 'The Rolling Stones' },
  { chapter: 'Shelly', song: "I Can't Tell You Why", artist: 'The Eagles' },
  { chapter: 'Thankful', song: 'You Are the Sunshine of My Life', artist: 'Stevie Wonder' },
  { chapter: 'Crustaceans', song: 'Rock Lobster', artist: "The B-52's" },
  { chapter: 'Secret Agent', song: 'Sister Christian', artist: 'Night Ranger' },
  { chapter: 'Octopus', song: 'Lost in the Flood', artist: 'Bruce Springsteen' },
  { chapter: 'Marrow of Life', song: 'Canon in D', artist: 'Pachelbel' },
  { chapter: 'Without Grace - Epilogue', song: 'Perfect Circle', artist: 'R.E.M.' },
]
